export class Constants {
    Race = {
        HUMAN: "人类",
        ELF: "精灵",
        DWARF: "矮人",
        HALFLING: "半身人",
        HALFELF: "半精灵",
        HALFORC: "半兽人",
        GNOME: "侏儒"
    };
    Class = {
        BARBARIAN: "野蛮人",
        BARD: "吟游诗人",
        CLERIC: "牧师",
        DRUID: "德鲁伊",
        FIGHTER: "战士",
        MONK: "武僧",
        PALADIN: "圣战士",
        RANGER: "巡林人",
        ROGUE: "游荡者",
        SORCERER: "术士",
        WIZARD: "法师",
    };
    Alignment = {
        LAWFUL_GOOD: "守序善良",
        NEUTRAL_GOOD: "中立善良",
        CHAOTIC_GOOD: "混乱善良",
        LAWFUL_NEUTRAL: "守序中立",
        TRUE_NEUTRAL: "绝对中立",
        CHAOTIC_NEUTRAL: "混乱中立",
        LAWFUL_EVIL: "守序邪恶",
        NEUTRAL_EVIL: "中立邪恶",
        CHAOTIC_EVIL: "混乱邪恶",
    };
    Religion = {
        NONE: "无",
        BACCOB: "博卡布",
        CORELLON_LARENTHIAN: "柯瑞隆‧拉瑞斯安",
        EHLONNA: "艾罗娜",
        ERYTNUL: "厄瑞斯努",
        FARLANGHN: "法兰恩",
        GARL_GLITTERGOLD: "加尔闪金",
        GRUUMSH: "格乌什",
        HEIRONEOUS: "海若尼斯",
        HEXTOR: "海克斯托",
        KORD: "寇德",
        MORADIN: "摩拉丁",
        NERULL: "奈落",
        OBAD_HAI: "欧拜‧亥",
        OLIDAMMARA: "渥利达马拉",
        PELOR: "培罗",
        ST_CUTHBERT: "圣‧库斯伯特",
        VECNA: "威可那",
        WEE_JAS: "维婕丝",
        YONDALLA: "悠达拉",
        OTHER_GOD: "其他",
    }
    ReligionAlignment = {
        NONE: "无",
        BACCOB: "魔法之神(绝对中立)",
        CORELLON_LARENTHIAN: "精灵之神(混乱善良)",
        EHLONNA: "森林女神(中立善良)",
        ERYTNUL: "杀戮之神(混乱邪恶)",
        FARLANGHN: "道路之神(绝对中立)",
        GARL_GLITTERGOLD: "侏儒之神(中立善良)",
        GRUUMSH: "兽人之神(混乱邪恶)",
        HEIRONEOUS: "勇者之神(守序善良)",
        HEXTOR: "暴虐之王(守序邪恶)",
        KORD: "力量之神(混乱善良)",
        MORADIN: "矮人之神(守序善良)",
        NERULL: "死亡之神(中立邪恶)",
        OBAD_HAI: "自然之神(绝对中立)",
        OLIDAMMARA: "游荡者之神(混乱中立)",
        PELOR: "太阳神(中立善良)",
        ST_CUTHBERT: "惩罚之神(守序中立)",
        VECNA: "私秘之神(中立邪恶)",
        WEE_JAS: "死亡与魔法女神(守序中立)",
        YONDALLA: "半身人女神(守序善良)",
        OTHER_GOD: "其他",
    }
}